version: '2'
services:
    php:
        build: ./docker/php
        restart: always
        volumes:
          - ./:/var/www/app
        container_name: 'App'

    nginx:
      image: nginx:latest
      restart: always
      ports:
        - "4888:80"
      volumes:
        - ./:/var/www/app
        - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
    mysql:
      image: mariadb:10.4
      restart: always
      ports:
        - "4333:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=celo
        - MYSQL_DATABASE=celo
      volumes:
        - ./docker/configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
